repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.8
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.33.0
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.1.0  # Use the sha / tag you want to point at
    hooks:
    - id: biome-check
      additional_dependencies: ["@biomejs/biome@1.4.1"]
